# Generated by Django 6.0.3 on 2026-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260417_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
